import Head from "next/head";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useRouter } from "next/router";
import {
  TitleWrapper,
  BackgroundImageWrapper,
  ImageSize,
  TypoWrapper,
  PeriodWrapper,
  Period,
  MapWrapper,
  MapTitle,
  Map,
} from "@src/components/Index/Index.styled";
import BackgroundImageUrl from "@public/images/index/index-background.png";
import { getRandomName } from "@src/utils/getRandomName";

export default function Home() {
  const { t } = useTranslation();
  const router = useRouter();
  const handleChange = (locale) => {
    router.push(router.pathname, router.asPath, { locale });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BackgroundImageWrapper>
        <ImageSize
          src={BackgroundImageUrl}
          alt="index-background"
          width={375}
          height={1262}
        />
        <TypoWrapper>
          <TitleWrapper>조선대 장미축제</TitleWrapper>
          <PeriodWrapper>
            <Period>2024. 05. 17(금)</Period>
            <Period>⸺</Period>
            <Period>2024. 05. 19(일)</Period>
          </PeriodWrapper>
        </TypoWrapper>
        <MapWrapper>
          <MapTitle>장미정원 조감도</MapTitle>
          <Map />
        </MapWrapper>
      </BackgroundImageWrapper>
    </>
  );
}

export async function getStaticProps(context) {
  const { locale } = context;
  return {
    props: {
      ...(await serverSideTranslations(locale)),
    },
  };
}
