import Head from "next/head";
import Image from "next/image";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useRouter } from "next/router";
import { IndexWrapper } from "@src/components/Index/Index.styled";
import BackImage from "@public/images/index/index-background.png";

export default function Home() {
  const { t } = useTranslation();
  const router = useRouter();
  const handleChange = (locale) => {
    router.push(router.pathname, router.asPath, { locale });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndexWrapper>
        <h1>{t("hello")}</h1>
        <button onClick={() => handleChange("ko")}>Change ko</button>
        <button onClick={() => handleChange("en")}>Change en</button>
      </IndexWrapper>
    </>
  );
}

export async function getStaticProps(context) {
  const { locale } = context;
  return {
    props: {
      ...(await serverSideTranslations(locale)),
    },
  };
}
